// <auto-generated/>
using BunnyApiClient.Models.StorageZone;
using BunnyApiClient.Storagezone.Checkavailability;
using BunnyApiClient.Storagezone.Item;
using BunnyApiClient.Storagezone.ResetReadOnlyPassword;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace BunnyApiClient.Storagezone
{
    /// <summary>
    /// Builds and executes requests for operations under \storagezone
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    public partial class StoragezoneRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The checkavailability property</summary>
        public global::BunnyApiClient.Storagezone.Checkavailability.CheckavailabilityRequestBuilder Checkavailability
        {
            get => new global::BunnyApiClient.Storagezone.Checkavailability.CheckavailabilityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The resetReadOnlyPassword property</summary>
        public global::BunnyApiClient.Storagezone.ResetReadOnlyPassword.ResetReadOnlyPasswordRequestBuilder ResetReadOnlyPassword
        {
            get => new global::BunnyApiClient.Storagezone.ResetReadOnlyPassword.ResetReadOnlyPasswordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the BunnyApiClient.storagezone.item collection</summary>
        /// <param name="position">The ID of the Storage Zone that should be returned</param>
        /// <returns>A <see cref="global::BunnyApiClient.Storagezone.Item.StoragezoneItemRequestBuilder"/></returns>
        public global::BunnyApiClient.Storagezone.Item.StoragezoneItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::BunnyApiClient.Storagezone.Item.StoragezoneItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BunnyApiClient.Storagezone.StoragezoneRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StoragezoneRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/storagezone?includeDeleted={includeDeleted}&page={page}&perPage={perPage}{&search*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BunnyApiClient.Storagezone.StoragezoneRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StoragezoneRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/storagezone?includeDeleted={includeDeleted}&page={page}&perPage={perPage}{&search*}", rawUrl)
        {
        }
        /// <summary>
        /// [ListStorageZones API Docs](https://docs.bunny.net/reference/storagezonepublic_index)
        /// </summary>
        /// <returns>A <see cref="global::BunnyApiClient.Storagezone.StoragezoneGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::BunnyApiClient.Storagezone.StoragezoneGetResponse?> GetAsync(Action<RequestConfiguration<global::BunnyApiClient.Storagezone.StoragezoneRequestBuilder.StoragezoneRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::BunnyApiClient.Storagezone.StoragezoneGetResponse> GetAsync(Action<RequestConfiguration<global::BunnyApiClient.Storagezone.StoragezoneRequestBuilder.StoragezoneRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::BunnyApiClient.Storagezone.StoragezoneGetResponse>(requestInfo, global::BunnyApiClient.Storagezone.StoragezoneGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// [AddStorageZone API Docs](https://docs.bunny.net/reference/storagezonepublic_add)
        /// </summary>
        /// <returns>A <see cref="global::BunnyApiClient.Models.StorageZone.StorageZone"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::BunnyApiClient.Models.StorageZone.StorageZone?> PostAsync(global::BunnyApiClient.Models.StorageZone.StorageZoneCreate body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::BunnyApiClient.Models.StorageZone.StorageZone> PostAsync(global::BunnyApiClient.Models.StorageZone.StorageZoneCreate body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::BunnyApiClient.Models.StorageZone.StorageZone>(requestInfo, global::BunnyApiClient.Models.StorageZone.StorageZone.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// [ListStorageZones API Docs](https://docs.bunny.net/reference/storagezonepublic_index)
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::BunnyApiClient.Storagezone.StoragezoneRequestBuilder.StoragezoneRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::BunnyApiClient.Storagezone.StoragezoneRequestBuilder.StoragezoneRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// [AddStorageZone API Docs](https://docs.bunny.net/reference/storagezonepublic_add)
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::BunnyApiClient.Models.StorageZone.StorageZoneCreate body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::BunnyApiClient.Models.StorageZone.StorageZoneCreate body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, "{+baseurl}/storagezone", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::BunnyApiClient.Storagezone.StoragezoneRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::BunnyApiClient.Storagezone.StoragezoneRequestBuilder WithUrl(string rawUrl)
        {
            return new global::BunnyApiClient.Storagezone.StoragezoneRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// [ListStorageZones API Docs](https://docs.bunny.net/reference/storagezonepublic_index)
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
        public partial class StoragezoneRequestBuilderGetQueryParameters 
        {
            [QueryParameter("includeDeleted")]
            public bool? IncludeDeleted { get; set; }
            [QueryParameter("page")]
            public int? Page { get; set; }
            [QueryParameter("perPage")]
            public int? PerPage { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("search")]
            public string? Search { get; set; }
#nullable restore
#else
            [QueryParameter("search")]
            public string Search { get; set; }
#endif
        }
    }
}
