// <auto-generated/>
#pragma warning disable CS0618
using EdgeStorageApiClient.Item.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace EdgeStorageApiClient.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \{storageZoneName}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithStorageZoneNameItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the EdgeStorageApiClient.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::EdgeStorageApiClient.Item.Item.WithPathItemRequestBuilder"/></returns>
        public global::EdgeStorageApiClient.Item.Item.WithPathItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("path", position);
                return new global::EdgeStorageApiClient.Item.Item.WithPathItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EdgeStorageApiClient.Item.WithStorageZoneNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithStorageZoneNameItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{storageZoneName}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EdgeStorageApiClient.Item.WithStorageZoneNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithStorageZoneNameItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{storageZoneName}", rawUrl)
        {
        }
        /// <summary>
        /// Builds and executes requests for operations under \{storageZoneName}\{+path}\
        /// </summary>
        /// <returns>A <see cref="global::EdgeStorageApiClient.Item.Item.WithPathSlashRequestBuilder"/></returns>
        /// <param name="path">The directory path that you want to list.</param>
        public global::EdgeStorageApiClient.Item.Item.WithPathSlashRequestBuilder WithPathSlash(string path)
        {
            if(string.IsNullOrEmpty(path)) throw new ArgumentNullException(nameof(path));
            return new global::EdgeStorageApiClient.Item.Item.WithPathSlashRequestBuilder(PathParameters, RequestAdapter, path);
        }
    }
}
#pragma warning restore CS0618
