// <auto-generated/>
#pragma warning disable CS0618
using EdgeStorageApiClient.Item.Item.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace EdgeStorageApiClient.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \{storageZoneName}\{+path}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithPathItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the EdgeStorageApiClient.item.item.item collection</summary>
        /// <param name="position">The name of the file that you wish to download.</param>
        /// <returns>A <see cref="global::EdgeStorageApiClient.Item.Item.Item.WithFileNameItemRequestBuilder"/></returns>
        public global::EdgeStorageApiClient.Item.Item.Item.WithFileNameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("fileName", position);
                return new global::EdgeStorageApiClient.Item.Item.Item.WithFileNameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EdgeStorageApiClient.Item.Item.WithPathItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithPathItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{storageZoneName}/{+path}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EdgeStorageApiClient.Item.Item.WithPathItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithPathItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{storageZoneName}/{+path}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
