// <auto-generated/>
#pragma warning disable CS0618
using BunnyApiClient.Shield.Metrics;
using BunnyApiClient.Shield.RateLimit;
using BunnyApiClient.Shield.RateLimits;
using BunnyApiClient.Shield.ShieldZone;
using BunnyApiClient.Shield.ShieldZones;
using BunnyApiClient.Shield.Waf;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BunnyApiClient.Shield
{
    /// <summary>
    /// Builds and executes requests for operations under \shield
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ShieldRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The metrics property</summary>
        public global::BunnyApiClient.Shield.Metrics.MetricsRequestBuilder Metrics
        {
            get => new global::BunnyApiClient.Shield.Metrics.MetricsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rateLimit property</summary>
        public global::BunnyApiClient.Shield.RateLimit.RateLimitRequestBuilder RateLimit
        {
            get => new global::BunnyApiClient.Shield.RateLimit.RateLimitRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rateLimits property</summary>
        public global::BunnyApiClient.Shield.RateLimits.RateLimitsRequestBuilder RateLimits
        {
            get => new global::BunnyApiClient.Shield.RateLimits.RateLimitsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The shieldZone property</summary>
        public global::BunnyApiClient.Shield.ShieldZone.ShieldZoneRequestBuilder ShieldZone
        {
            get => new global::BunnyApiClient.Shield.ShieldZone.ShieldZoneRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The shieldZones property</summary>
        public global::BunnyApiClient.Shield.ShieldZones.ShieldZonesRequestBuilder ShieldZones
        {
            get => new global::BunnyApiClient.Shield.ShieldZones.ShieldZonesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The waf property</summary>
        public global::BunnyApiClient.Shield.Waf.WafRequestBuilder Waf
        {
            get => new global::BunnyApiClient.Shield.Waf.WafRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BunnyApiClient.Shield.ShieldRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ShieldRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/shield", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BunnyApiClient.Shield.ShieldRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ShieldRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/shield", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
