// <auto-generated/>
using BunnyApiClient.Pullzone.Item.Edgerules.AddOrUpdate;
using BunnyApiClient.Pullzone.Item.Edgerules.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BunnyApiClient.Pullzone.Item.Edgerules
{
    /// <summary>
    /// Builds and executes requests for operations under \pullzone\{-id}\edgerules
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public partial class EdgerulesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The addOrUpdate property</summary>
        public global::BunnyApiClient.Pullzone.Item.Edgerules.AddOrUpdate.AddOrUpdateRequestBuilder AddOrUpdate
        {
            get => new global::BunnyApiClient.Pullzone.Item.Edgerules.AddOrUpdate.AddOrUpdateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the BunnyApiClient.pullzone.item.edgerules.item collection</summary>
        /// <param name="position">The ID of the Edge Rule that should be deleted</param>
        /// <returns>A <see cref="global::BunnyApiClient.Pullzone.Item.Edgerules.Item.WithEdgeRuleItemRequestBuilder"/></returns>
        public global::BunnyApiClient.Pullzone.Item.Edgerules.Item.WithEdgeRuleItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("edgeRuleId", position);
                return new global::BunnyApiClient.Pullzone.Item.Edgerules.Item.WithEdgeRuleItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BunnyApiClient.Pullzone.Item.Edgerules.EdgerulesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EdgerulesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/pullzone/{%2Did}/edgerules", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BunnyApiClient.Pullzone.Item.Edgerules.EdgerulesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EdgerulesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/pullzone/{%2Did}/edgerules", rawUrl)
        {
        }
    }
}
