// <auto-generated/>
#pragma warning disable CS0618
using BunnyApiClient.Shield.Metrics.Waf.Blocked;
using BunnyApiClient.Shield.Metrics.Waf.Logged;
using BunnyApiClient.Shield.Metrics.Waf.Processed;
using BunnyApiClient.Shield.Metrics.Waf.Triggered;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BunnyApiClient.Shield.Metrics.Waf
{
    /// <summary>
    /// Builds and executes requests for operations under \shield\metrics\waf
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WafRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The blocked property</summary>
        public global::BunnyApiClient.Shield.Metrics.Waf.Blocked.BlockedRequestBuilder Blocked
        {
            get => new global::BunnyApiClient.Shield.Metrics.Waf.Blocked.BlockedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The logged property</summary>
        public global::BunnyApiClient.Shield.Metrics.Waf.Logged.LoggedRequestBuilder Logged
        {
            get => new global::BunnyApiClient.Shield.Metrics.Waf.Logged.LoggedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The processed property</summary>
        public global::BunnyApiClient.Shield.Metrics.Waf.Processed.ProcessedRequestBuilder Processed
        {
            get => new global::BunnyApiClient.Shield.Metrics.Waf.Processed.ProcessedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The triggered property</summary>
        public global::BunnyApiClient.Shield.Metrics.Waf.Triggered.TriggeredRequestBuilder Triggered
        {
            get => new global::BunnyApiClient.Shield.Metrics.Waf.Triggered.TriggeredRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BunnyApiClient.Shield.Metrics.Waf.WafRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WafRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/shield/metrics/waf", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BunnyApiClient.Shield.Metrics.Waf.WafRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WafRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/shield/metrics/waf", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
