// <auto-generated/>
#pragma warning disable CS0618
using BunnyApiClient.Shield.ShieldZone.GetByPullzone.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BunnyApiClient.Shield.ShieldZone.GetByPullzone
{
    /// <summary>
    /// Builds and executes requests for operations under \shield\shield-zone\get-by-pullzone
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetByPullzoneRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the BunnyApiClient.shield.shieldZone.getByPullzone.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::BunnyApiClient.Shield.ShieldZone.GetByPullzone.Item.WithPullZoneItemRequestBuilder"/></returns>
        public global::BunnyApiClient.Shield.ShieldZone.GetByPullzone.Item.WithPullZoneItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("pullZoneId", position);
                return new global::BunnyApiClient.Shield.ShieldZone.GetByPullzone.Item.WithPullZoneItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BunnyApiClient.Shield.ShieldZone.GetByPullzone.GetByPullzoneRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetByPullzoneRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/shield/shield-zone/get-by-pullzone", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BunnyApiClient.Shield.ShieldZone.GetByPullzone.GetByPullzoneRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetByPullzoneRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/shield/shield-zone/get-by-pullzone", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
